### ISSUE TITLE
Fix automated tests

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/phpexcel#5]
Per discussion in https://github.com/backdrop-contrib/phpexcel/issues/3#issuecomment-2007458547, the automated tests fail with PHP 8.1 and current Backdrop installation. Fixing those will probably improve general performance in PHP 8.1.

Also, one of the tests (`testDBResultExport`) fails because Backdrop has changed the default number of nodes in a new installation. This test should be updated to be independent of the number of preexisting node.

PR to follow.

**Comment by VasasA** [comment]
@bugfolder Thank You for the PR.
After the merging, I created a new commit: fix - creation of dynamic property is deprecated
Can you suggest a new release (1.x-3.11.2) to publish?

**Comment by bugfolder** [comment]
Yes, I think it's now ready for a new release. Thanks for merging!
